### ISSUE TITLE
Dataset query image generation rule

### ISSUE THREAD

**Issue by whu-lyh** [amaralibey/gsv-cities#17]
Hi? May I ask how to select the query images and to create the following npy file? using MSLS dataset as an example.
```
self.dbImages = np.load(GT_ROOT+'msls_val/msls_val_dbImages.npy')
self.qIdx = np.load(GT_ROOT+'msls_val/msls_val_qIdx.npy')
self.qImages = np.load(GT_ROOT+'msls_val/msls_val_qImages.npy')
self.ground_truth = np.load(GT_ROOT+'msls_val/msls_val_pIdx.npy', allow_pickle=True)
```
I am trying to build my own datasets and test your models

**Comment by amaralibey** [comment]
Hello @whu-lyh,

Printing the numpy objects will provide a visual representation of how they were created.

We aim to populate the `dbImages.npy` file with filenames of reference images to avoid the need for  listing a directory and reading the image names one by one. Similarly, we intend to store the filenames of query images in the `qImages.npy` file.

In certain datasets, not all queries are taken into consideration, which is why a `qIdx.npy` is utilized. This array contains the indices of the queries that are actually used.

Additionally, there is a `ground_truth` list of lists, where each inner list corresponds to a specific query. To be precise, `ground_truth[0]` is a list containing the indices from `dbImages.npy` that represent positive matches for the first query, specifically `qImages[qIdx[0]]`.

**Comment by whu-lyh** [comment]
Well. Thank you very much. About sequence images，how should I filter the images as query? May be a constant distance，e.g. 10m, to select one image?

**Comment by amaralibey** [comment]
@whu-lyh,
In general, in Visual Place Recognition, images are considered to belong to the same place if they are less than 25 meters appart. There is no theoretical explanation behind this, it's just that the first authors used this distance and we followed along.

To create a query and identify its associated positive images, you can consider selecting images that are within a maximum distance of 25 meters from the query as correct matches.

When creating multiple queries, ensure that there is a minimum distance of 50 meters between each other to avoid any overlap.

**Comment by whu-lyh** [comment]
I got it, thanks!!
