### ISSUE TITLE
about running problem

### ISSUE THREAD

**Issue by pfywjk** [amaralibey/gsv-cities#18]
Hello，I have some question about training. I met a problem When I tried to run the main.py . According to the prompt, I tried modifying the value of the max_steps, but it still shows max_steps=1. Can you give me some suggestions about this problem?
![3EXOF GRN}%VP68N13U{{QY](https://github.com/amaralibey/gsv-cities/assets/76151744/47f5dd0b-ed4e-460a-8b4c-ee9ecb413771)

**Comment by amaralibey** [comment]
Hello @pfywjk,

That's because you're running in dev mode where we only run one iteration to see if everything works fine. In order to start training, just comment the following line https://github.com/amaralibey/gsv-cities/blob/77ffffc23115e5ba966e108895343693ec49cbb2/main.py#L316C35-L316C35

Best regards,

**Comment by pfywjk** [comment]
Hello @amaralibey ，
Thank you very much! I successfully solved the problem.
